on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n Sarthak0 -g Sarthak0b788-rg --location "Central India" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n Sarthak0 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n Sarthak0 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n Sarthak0 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: sarthak0.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/hello-world" -f  "hello-world" -t sarthak0.azurecr.io/sarthak:${{ github.sha }}
        docker push sarthak0.azurecr.io/sarthak:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_sarthak_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sarthak6832 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sarthak6832`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sarthak6832
        container-registry-url: sarthak0.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: sarthakdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: sarthak6832
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          sarthak0.azurecr.io/sarthak:${{ github.sha }}
        imagepullsecrets: |
          sarthakdockerauth